name: Test build of image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build service
        run: |
          docker build . -f Dockerfile -t samgozman:latest
